export const WEB_COPY = {
  header: {
    appPromoTitlePrefix: 'Get the',
    appPromoTitleSuffix: 'App',
    appPromoDescription: 'Use the app for a smoother shopping and checkout experience.',
    continueOnWebsite: 'Continue on website',
    cartLabel: 'Cart',
    confirmLogoutTitle: 'Confirm Logout',
    confirmLogoutDescription: 'Are you sure you want to log out? You can sign in again anytime.',
    confirmLogoutAction: 'Yes, Log Out',
  },
  login: {
    otpVerificationTitle: 'OTP Verification',
    signupHint: 'Sign up with mobile OTP',
    signinHint: 'Sign in with mobile OTP',
    mobilePlaceholder: 'Enter 10-digit mobile number',
    sendOtp: 'Send OTP',
    verifyContinue: 'Verify & Continue',
    verifySignIn: 'Verify & Sign In',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    backToSignIn: '← Back to Sign In',
    backToSignUp: '← Back to Sign Up',
    securityFooter: 'Secured sign-in • OTP verified',
  },
  cart: {
    myCart: 'My Cart',
    itemCountSuffix: 'item(s)',
    freeDeliveryUnlocked: 'Free delivery unlocked',
    addMoreForFreeDelivery: (amount: number | string) => `Add ₹${amount} more for free delivery`,
    deliveryFeeSaved: 'Delivery fee saved',
    emptyCart: 'Your cart is empty',
  },
} as const;
